language: go
dist: bionic
sudo: required
arch:
  - ppc64le
go:
  - 1.15.5
env:
  matrix:
  - OS_TYPE=ubi8.3  
  
services:
  - docker


script:
  - make install-sdk
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make install-tools
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make test
  
 
