language: go
sudo: required
dist: bionic
arch:
  - ppc64le
go:
  - 1.16.5
services:
  - docker
  
env:
- CHANGE_MINIKUBE_NONE_USER=true

before_script:
- sudo systemctl enable docker.service
- sudo apt-get install -y conntrack
- make install-sdk
- sudo apt-get install linux-image-$(uname -r)


script:
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make install-tools
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make
  - make test
  
 
