language: go
sudo: required

arch:
  - ppc64le
go:
  - 1.16.5
env:
  matrix:
  - OS_TYPE=ubi8.3  OS_VERSION=6
  
services:
  - docker
before_install:
  - docker run -it --name jaeger  registry.access.redhat.com/ubi8/ubi:8.3 bash



script:
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make install-tools
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make test
  
 
