language: go
sudo: required
dist: bionic
arch:
  - ppc64le
go:
  - 1.16.5
services:
  - docker




script:
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make install-tools
  - GO_FLAGS="GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on" make
  - make test
  
 
