language: go


arch:
  - ppc64le
go:
  - 1.16.5
env:
  matrix:
  - OS_TYPE=ubi8.3  
  
services:
  - docker




script:
  - git clone https://github.com/operator-framework/operator-sdk
  - cd operator-sdk
  - git checkout master
  - make install
  - make build test
  
 
